KOGITO-2770
kiegroup/drools-wb pull request #1432
Opened 2020-10-15 09:48 UTC by yesamer

**JIRA**: https://issues.redhat.com/browse/KOGITO-2770

**referenced Pull Requests**:
* https://github.com/kiegroup/drools/pull/3168

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2020-10-20 07:02 UTC, Rikkola commented
@yesamer Was this issue just in kogito or also in business central?

2020-10-20 07:22 UTC, yesamer commented
@Rikkola The changes will have impact on both BC and Kogito (VSCode). I'll provide a a full description later today.

2020-10-22 09:15 UTC, Rikkola approved these changes

2020-10-22 12:19 UTC, yesamer commented
jenkins retest this please

2020-10-26 12:23 UTC, jstastny-cz requested changes

2020-10-26 12:23 UTC, jstastny-cz commented
jenkins do fdb

2020-10-26 13:11 UTC, yesamer commented
jenkins do fdb

2020-10-26 13:15 UTC, yesamer commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationContext.java
> +    private static final String ILLEGAL_WIDGET_MESSAGE = "Illegal GridWidget ";
@jstastny-cz  Done!

2020-10-26 13:15 UTC, yesamer commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractScenarioSimulationUndoableCommand.java
> +            String message = this.getClass().getSimpleName() + "restorableStatus status is null";
@jstastny-cz  Done!

2020-10-26 13:15 UTC, yesamer commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/UpdateSettingsDataCommand.java
> +                throw new IllegalStateException("restorableSettings is null");
@jstastny-cz  Done!

2020-10-26 13:15 UTC, yesamer commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsPresenter.java
> +            throw new IllegalStateException("Trying to update a " + settings.getType() + " data ");
@jstastny-cz  Done!

2020-10-26 13:15 UTC, yesamer commented on drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java
> +        //verify(scenarioGridWidgetSpy, times(1)).setContent(eq(content.getModel().getSimulation()), eq(scenarioSimulationContextLocal.getStatus().getSettings().getType()));
@jstastny-cz  Done!

2020-11-09 14:41 UTC, jstastny-cz commented
jenkins do fdb

2020-11-10 08:13 UTC, jstastny-cz commented
Even though FDB failed the business central war was built successfully, continuing with testing.

2020-11-10 09:19 UTC, jstastny-cz commented
BC - the editor is not locked when a change is done in settings panel. User does not have the feedback that the contents are eing edited by someone else until the other person saves the changes.

2020-11-10 13:02 UTC, yesamer commented
@jstastny-cz Unfortunately the locking mechanism you mentioned works differently in BC. Considering this PR is mostly for KOGITO, I propose to manage the BC "isDirty" status in a different ticket. This because, if the PR works correctly in Kogito, I would prefer to don't block it.

2020-11-12 13:23 UTC, yesamer commented
@jstastny-cz I tested the behavior in BC, and it seems correct to me. I opened a scesim file, I modified on parameter in Settings Dock and, if i try to leave without saving, a popup which warns the user of unsaved changes appears. If I undo the change and I close the editor, no message is shown as expected.

2020-11-12 13:42 UTC, jstastny-cz commented
@yesamer yep that part works fine, just the locking does not work. I can state that as a non-goal for the feature and it would be ok to merge as is.

2020-11-12 14:17 UTC, jstastny-cz approved these changes
LGTM, we've come up to conclusion that the discussed behavior is in sync with what we have for other editors. Stating this explicitly as a non-goal for this feature, approving.

2020-11-12 16:10 UTC, yesamer commented
@kiegroup/gatekeepers Can you please merge it?

2020-11-12 16:23 UTC, merged