DROOLS-5808 : XLS to GDST conversion should ensure types work
kiegroup/drools-wb pull request #1441
Opened 2020-11-12 08:19 UTC by Rikkola

DROOLS-5807 : GDST to XLS conversion should not convert dialect column

Moving few classes from drools-wb so they can be used by both GDST->XLS and XLS-GDST conversion.

**JIRA**: [DROOLS-5807](https://issues.redhat.com/browse/DROOLS-5807)
**JIRA**: [DROOLS-5808](https://issues.redhat.com/browse/DROOLS-5808)

 
**Referenced Pull Requests**:
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>

2020-11-12 08:21 UTC, Rikkola commented on drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/conversion/BRLColumnSubHeaderBuilderDefault.java
> +            if (brlConditionVariableColumn.getVarName() == null || brlConditionVariableColumn.getVarName().isEmpty()) {
3rd issue the file found, but I did not make an ticket for it. BRL columns with no variables caused an NPE here.

2020-11-18 13:39 UTC, vpellegrino requested changes
I've added minor comments. Overall code looks clear to me

2020-11-18 13:39 UTC, vpellegrino commented on drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/conversion/BRLColumnDataBuilderDefault.java
>                      return false;
```suggestion
                final String variableName = getVariableName(childColumn);
                return StringUtils.isEmpty(variableName);
```

2020-11-18 13:39 UTC, vpellegrino commented on drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/conversion/BRLColumnSubHeaderBuilderDefault.java
> +            if (brlConditionVariableColumn.getVarName() == null || brlConditionVariableColumn.getVarName().isEmpty()) {
Also there. I think that the usage of `StringUtils.isEmpty()` whould make statement more readable.

2020-11-18 13:39 UTC, vpellegrino commented on drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/conversion/util/Skipper.java
> +            notificationReporter.report("Dialect is not a supported column type in XLS Decision tables. Conversion ignored this column.");
this string is not translated by any i18n service?

2020-11-18 18:21 UTC, Rikkola commented
Not sure how I mixed these, but these are the wrong conversion fixes. Closing the PRs for now.

2020-11-18 18:21 UTC, closed without merging